"""add tokens_used

Revision ID: 1075cfe14f9a
Revises: f66e52bcdbb5
Create Date: 2023-02-02 15:43:57.457056

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1075cfe14f9a'
down_revision = 'f66e52bcdbb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tokens_used', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tokens_used')
    # ### end Alembic commands ###
